### ISSUE TITLE
Does not play well with DI Containers

### ISSUE THREAD

**Issue by andrewf-ccl** [bunsen32/typed-url-routing#2]
typed-url-routing attempted to construct Controllers by just instantiating the class.

This does not work if the Controller class has dependencies.

Change Controller construction to use the DI container (if available). Should fall back to existing behaviour.

**Comment by bunsen32** [comment]
Does now. Fairly easy fix. Just needed to obtain Controller object using `DependencyResolver.Current.GetService<C>()` instead of `Activator`.
