### ISSUE TITLE
Does not resolve Async Controller methods

### ISSUE THREAD

**Issue by andrewf-ccl** [bunsen32/typed-url-routing#3]
The matching process (of UrlPattern to Controller Action method) does not handle Async action methods which have return type of Task or Task<T>.

**Comment by bunsen32** [comment]
Totally does resolve it now.

The action invocation code is cribbed from Microsoft’s ASP.NET source code.

Currently fails to pass through `HttpContext.Current` to the callback which executes the ActionResult after the action has completed. Unclear why this is not working, but it breaks AutoFac Dependency Injection, so have raised as new issue, #6.
